<?php

/**
 * Implements hook_menu().
 */
function flag_application_menu() {
  $items['admin/structure/flags/flag_application'] = array(
    'title' => 'Flag applications',
    'description' => 'Find and manage flag applications.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_admin_content'),
    'access callback' => 'flag_application_permission',
    //'access arguments' => array(1, 'delete'),
    'weight' => 0,
    'file' => 'flag_application.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission
 */
function flag_application_permission() {
  return TRUE;
}


/**
 * Implements hook_flag_flag
 */
function flag_application_flag_flag($flag, $entity_id, $account, $flagging) {
	dsm($flagging);
	if ($flag->name == 'flag_application') {
		$result = db_insert('flag_application')
			->fields(array(
				'flag_application' => $flagging->flagging_id,
				'status' => 0,
			))
			->execute();
	}
}

/**
 * Implements hook_flag_unflag 
 */
function flag_application_flag_unflag($flag, $entity_id, $account, $flagging) {
	if ($flag->name == 'flag_application') {
		$deleted = db_delete('flag_application')
			->condition('flag_application', $flagging->flagging_id)
			->execute();
	}
}

/**
 * Implements hook_flag_default_flags.
 */
function flag_application_flag_default_flags() {
  $flags = array();
  $flags['flag_application'] = array(
    'entity_type' => 'node',
    'title' => 'Flag Application',
    'global' => FALSE,
    'types' => array(
      0 => 'article',
      1 => 'blog',
    ),
    'flag_short' => 'Flag Application this',
    'flag_long' => 'Add this post to your Flag Application',
    'flag_message' => 'This post has been added to your Flag Application',
    'unflag_short' => 'Unflag this',
    'unflag_long' => 'Remove this post from your Flag Application',
    'unflag_message' => 'This post has been removed from your Flag Application',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'weight' => 0,
    'show_in_links' => array(
      'full' => TRUE,
      'token' => FALSE,
    ),
    'show_as_field' => FALSE,
    'show_on_form' => FALSE,
    'access_author' => '',
    'show_contextual_link' => TRUE,
    'show_on_profile' => FALSE,
    'access_uid' => '',
    'api_version' => 3,
  );
  return $flags;
}

?>