<?php

/**
 * Implements hook_menu().
 */
function flag_application_menu() {
  $items['admin/structure/flags/flag_application'] = array(
    'title' => 'Flag applications',
    'description' => 'Find and manage flag applications.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_admin_content'),
    'access callback' => 'flag_application_permission',
    'weight' => 0,
    'file' => 'flag_application.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission
 */
function flag_application_permission() {
  return TRUE;
}


/**
 * Implements hook_flag_flag
 */
function flag_application_flag_flag($flag, $entity_id, $account, $flagging) {
	dsm($flagging);
	if ($flag->name == 'flag_application') {
		$result = db_insert('flag_application')
			->fields(array(
				'flag_application' => flagging->$flagging_id,
				'status' => 0,
			))
			->execute();
	}
}

/**
 * Implements hook_flag_unflag 
 */
function flag_application_flag_unflag($flag, $entity_id, $account, $flagging) {
	if ($flag->name == 'flag_application') {
		$deleted = db_delete('flag_application')
			->condition('flag_application' => flagging->$flagging_id)
			->execute();
	}
}

/**
 * Implements hook_flag_default_flags
 */
function flag_application_default_flags() {
  $flags = array();
  $flags['flag_application'] = array (
	  'entity_type' => 'node',
	  'title' => 'Flag Application',
	  'global' => '0',
	  'types' => 
	  array (
	  ),
	  'flag_short' => 'Apply',
	  'flag_long' => 'Apply for this',
	  'flag_message' => 'Thanks for applying',
	  'unflag_short' => 'Remove your application for this form the site',
	  'unflag_long' => 'Your application have been removed',
	  'unflag_message' => '',
	  'unflag_denied_text' => '',
	  'link_type' => 'toggle',
	  'weight' => 0,
	  'show_in_links' => 
	  array (
		'full' => 'full',
		'teaser' => 0,
		'rss' => 0,
		'search_index' => 0,
		'search_result' => 0,
	  ),
	  'show_as_field' => 1,
	  'show_on_form' => 0,
	  'access_author' => '',
	  'show_contextual_link' => 0,
	  'i18n' => 0,
	  'api_version' => 3,
	);
  return $flags;
}
?>